### ISSUE TITLE
Problem in Trust Region Dogleg

### ISSUE THREAD

**Issue by GermanHeim** [argmin-rs/argmin#571]
Hello,
I am facing the following issue while using Dogleg:

```
the trait bound `ArrayBase<OwnedRepr<f64>, Dim<[usize; 2]>>: argmin_math::ArgminInv<ArrayBase<OwnedRepr<f64>, Dim<[usize; 2]>>>` is not satisfied
the trait `argmin_math::ArgminInv<ArrayBase<OwnedRepr<f64>, Dim<[usize; 2]>>>` is not implemented for `ArrayBase<OwnedRepr<f64>, Dim<[usize; 2]>>`
the trait `Solver<O, IterState<P, G, (), H, (), F>>` is implemented for `TrustRegion<R, F>`
required for `Dogleg<f64>` to implement `Solver<LocalSolver<P>::solve_trust_region::ProblemCost<'_, P>, IterState<ArrayBase<OwnedRepr<f64>, Dim<[usize; 1]>>, ArrayBase<OwnedRepr<f64>, Dim<[usize; 1]>>, (), ArrayBase<OwnedRepr<f64>, Dim<[usize; 2]>>, (), f64>>`
```

My code:
```rust
                TrustRegionRadiusMethod::Dogleg => {
                    let subproblem = Dogleg::new();
                    let solver = TrustRegion::new(subproblem)
                        .with_radius(*radius)
                        .map_err(|e| LocalSolverError::InvalidTrustRegionConfig(e.to_string()))?
                        .with_max_radius(*max_radius)
                        .map_err(|e| LocalSolverError::InvalidTrustRegionConfig(e.to_string()))?
                        .with_eta(*eta)
                        .map_err(|e| LocalSolverError::InvalidTrustRegionConfig(e.to_string()))?;
                    let res = Executor::new(cost, solver)
                        .configure(|state| state.param(initial_point.clone()))
                        .run()
                        .map_err(|e: Error| LocalSolverError::RunFailed(e.to_string()))?;
```

It works fine with Cauchy.

These are my dependencies:
```toml
[dependencies]
argmin = { version = "0.10.0" }
argmin-math = { version = "0.4.0", features = ["ndarray_latest-nolinalg"] }
ndarray = "0.15.6"
rayon = { version = "1.5.3", optional = true }
thiserror = "2.0.11"
rand = "0.9.0"
```

I don't know what is causing it. Is it a problem with `argmin-math`?
